import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { createStore } from "little-state-machine";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

createStore({
  cart: [],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
